"""empty message

Revision ID: 32ef90d92385
Revises: 445a7992712a
Create Date: 2020-12-18 07:06:22.306095

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '32ef90d92385'
down_revision = '445a7992712a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('datstart_time', sa.DateTime(), nullable=True))
    op.drop_column('show', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('show', 'datstart_time')
    # ### end Alembic commands ###
