"""empty message

Revision ID: 445a7992712a
Revises: 4bda4b8d98f5
Create Date: 2020-12-18 03:25:31.919740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '445a7992712a'
down_revision = '4bda4b8d98f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('Artist_id', sa.Integer(), nullable=False))
    op.add_column('show', sa.Column('Venue_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'show', 'Artist', ['Artist_id'], ['id'])
    op.create_foreign_key(None, 'show', 'Venue', ['Venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.drop_column('show', 'Venue_id')
    op.drop_column('show', 'Artist_id')
    # ### end Alembic commands ###
